# Generated by Django 5.0.7 on 2024-08-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('address', models.DateField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('passind_year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
